-- ooxml-editorial-marks.lua
--
-- Translates Quarto's editorial-mark AST nodes into native Office Open XML
-- (OOXML) comments and track-changes markup for docx, and best-effort visual
-- fallbacks for pptx (which has no track-changes/comment concept reachable
-- from a Lua AST filter).
--
-- Quarto's qmd syntax --
--   [++ text]   / ::: ++   -> insertion
--   [-- text]   / ::: --   -> deletion
--   [!! text]   / ::: !!   -> highlight
--   [>> text]   / ::: >>   -> comment
-- -- is desugared by pampa (see q2's crates/pampa/src/pandoc/treesitter_utils/
-- postprocess.rs and editorial_div.rs) into plain Pandoc Span (inline) or Div
-- (block) nodes whose *first* class is one of:
--   quarto-insert | quarto-delete | quarto-highlight | quarto-edit-comment
-- Any user-supplied classes follow after that first class. id and key-value
-- attributes survive verbatim -- quarto-edit-comment spans/divs commonly
-- carry author= and date= (see q2's crates/quarto-core/src/document_profile.rs
-- for the canonical shape hub-client relies on).
--
-- DOCX strategy (empirically verified against pandoc 3.11's Haskell writer,
-- resources/pandoc/src/Text/Pandoc/Writers/Docx/OpenXML.hs):
--   - A Span with class "insertion" (any other classes/attrs/id are fine
--     alongside it -- the writer checks list membership) becomes a native
--     <w:ins w:id=".." w:author=".." w:date="..">, auto-numbered by pandoc
--     itself. Class "deletion" is the <w:del>/<w:delText> equivalent.
--   - A *bare* Span with attr exactly ("", {"mark"}, {}) -- no id, no extra
--     classes, no kvs -- becomes a native run with <w:highlight w:val="yellow"/>.
--     This pattern match is narrow: any extra id/class/kv on the Span falls
--     through to generic handling with NO highlight applied. So
--     handle_highlight intentionally discards id/extra classes/kvs; there is
--     no OOXML home for them on a highlighted run anyway.
--   - None of the above apply to Div (block) nodes -- the writer ignores a
--     Div's classes entirely. Block-level marks are handled by wrapping each
--     leaf paragraph's *inline content* in the same marker Span, recursively,
--     so the run-level native handling above still applies once each
--     paragraph is individually written.
--   - A Span with class "comment-start" is special: its *content* becomes
--     the comment's text in word/comments.xml (not visible body text), and
--     it emits a zero-width <w:commentRangeStart>. A matching "comment-end"
--     Span (same "id" kv) emits <w:commentRangeEnd> + <w:commentReference>,
--     and *its* content (if any) is rendered as ordinary visible body text.
--     Content-type/relationship registrations and comments.xml itself are
--     all generated by pandoc automatically -- no zip-level post-processing
--     needed, contrary to the assumption in this repo's README.
--   - A comment nested inside another comment must fold into the outer
--     comment's text rather than becoming its own separate Word comment (see
--     document_profile.rs's `profile_extract_block_comment_is_a_leaf` test).
--     This filter achieves that with `traverse = "topdown"` plus returning
--     `false` from handle_edit_comment: once an outer comment is replaced,
--     its original (pre-replacement) inline/block content is reused verbatim
--     as the comment-start Span's content, and we never re-descend into it,
--     so any nested quarto-* mark inside is left with its original
--     (unrecognized-by-the-writer) class and just renders as plain text --
--     exactly the fold-in behavior we want, with no manual text-flattening.
--
-- PPTX strategy: PowerPoint has no writer-level support for any of the above
-- classes (verified: Powerpoint/Presentation.hs ignores Span classes
-- entirely and has no insertion/deletion/mark/comment handling at all), and
-- no inline-anchored "real" comment concept reachable from an AST filter
-- (pptx comments are anchored to a slide position, not a text range). We
-- fall back to visual approximations built from raw OOXML paragraph
-- elements (`pandoc.RawInline("openxml", ...)`, which Powerpoint/
-- Presentation.hs's `inlineToParElems` turns into a `RawOOXMLParaElem`
-- sibling of `<a:r>` runs): underline for insertions, strikethrough for
-- deletions, a highlight fill for highlights, and a bracketed inline
-- annotation for comments. These are single flattened runs (via
-- pandoc.utils.stringify), so nested rich formatting inside a pptx mark is
-- lost -- a documented limitation, not an oversight.

if not (FORMAT == "docx" or FORMAT == "pptx") then
  return {}
end

local function first_class(el)
  return el.classes[1]
end

local QUARTO_MARK_CLASSES = {
  ["quarto-insert"] = true,
  ["quarto-delete"] = true,
  ["quarto-highlight"] = true,
  ["quarto-edit-comment"] = true,
}

local function is_quarto_mark(block)
  return block.classes and QUARTO_MARK_CLASSES[block.classes[1]]
end

-- Forward declaration: assigned once the docx/pptx dispatch tables exist
-- (bottom of file). Needed here because block-wrapping helpers below must
-- recursively re-dispatch a nested quarto-* mark themselves: pandoc's
-- `traverse = "topdown"` walk does NOT re-descend into a `Blocks`/`Inlines`
-- *list* returned as a replacement (verified empirically -- only a
-- single-node replacement gets walked further), so relying on the walker to
-- separately visit a nested mark left untouched inside such a list would
-- silently skip it.
local dispatch_element

--------------------------------------------------------------------------
-- Shared helpers
--------------------------------------------------------------------------

-- Replace `el`'s first class (the quarto-* marker) with `new_class`,
-- keeping id, remaining user classes, and all attributes untouched.
local function with_first_class_replaced(el, new_class)
  local classes = {}
  for i, c in ipairs(el.classes) do
    if i == 1 then
      classes[i] = new_class
    else
      classes[i] = c
    end
  end
  local new_el = el:clone()
  new_el.classes = classes
  return new_el
end

-- Wrap every paragraph-like block's inline content, at any depth, in a Span
-- with `attr`. Used to bring block-level (Div) marks down to the run level,
-- since pandoc's docx writer only special-cases Span classes. A nested
-- quarto-* mark is converted to its own native form directly (and not
-- descended into): the walk below would otherwise wrap its paragraphs too.
-- CodeBlocks have no run-level home for the marker and are left as-is.
local function wrap_blocks_with_span(blocks, attr)
  local function wrap(block)
    local new_block = block:clone()
    new_block.content = pandoc.Inlines({ pandoc.Span(block.content, attr) })
    return new_block, false
  end
  return pandoc.Blocks(blocks):walk({
    traverse = "topdown",
    Div = function(div)
      if is_quarto_mark(div) then
        return dispatch_element(div), false
      end
    end,
    Para = wrap,
    Plain = wrap,
    Header = wrap,
  })
end

--------------------------------------------------------------------------
-- docx handlers
--------------------------------------------------------------------------

--- Emit a Word `<w:ins>` run (inline) or wrap each paragraph's runs in one
--- (block), via pandoc's native "insertion" class support. w:author/w:date
--- come from el.attributes.author / .date when present (pandoc defaults
--- w:author to "unknown" itself when absent); w:id is auto-numbered by
--- pandoc, so no id management is needed here.
local function docx_handle_insert(el)
  if el.t == "Div" then
    local attr = pandoc.Attr("", { "insertion" }, {})
    return wrap_blocks_with_span(el.content, attr)
  end
  return with_first_class_replaced(el, "insertion")
end

--- Emit a Word `<w:del>`/`<w:delText>` run, via pandoc's native "deletion"
--- class support. Deleted content is not rendered as ordinary visible text
--- once opened in Word with track changes displayed.
local function docx_handle_delete(el)
  if el.t == "Div" then
    local attr = pandoc.Attr("", { "deletion" }, {})
    return wrap_blocks_with_span(el.content, attr)
  end
  return with_first_class_replaced(el, "deletion")
end

--- Emit a Word run with `<w:highlight w:val="yellow"/>` shading, via
--- pandoc's native (narrowly-matched) bare ("", {"mark"}, {}) Span support.
--- id / extra classes / extra kv attributes are intentionally dropped: the
--- writer only applies the highlight when the Span carries nothing else,
--- and there is no OOXML equivalent for arbitrary metadata on a highlighted
--- run.
local function docx_handle_highlight(el)
  local attr = pandoc.Attr("", { "mark" }, {})
  if el.t == "Div" then
    return wrap_blocks_with_span(el.content, attr)
  end
  return pandoc.Span(el.content, attr)
end

local comment_counter = 0
local function next_comment_id(el)
  if el.identifier and el.identifier ~= "" then
    return el.identifier
  end
  comment_counter = comment_counter + 1
  return "quarto-comment-" .. tostring(comment_counter)
end

-- Only author/date have an OOXML home on <w:comment> (plus w:initials,
-- which quarto-edit-comment marks don't carry); other kv attributes (e.g.
-- a stray `key="value"`) have nowhere valid to go and are dropped.
local function comment_attrs(el, id)
  local attrs = { { "id", id } }
  local author = el.attributes["author"]
  local date = el.attributes["date"]
  if author then table.insert(attrs, { "author", author }) end
  if date then table.insert(attrs, { "date", date }) end
  return attrs
end

--- Emit an OOXML comment: a zero-width `<w:commentRangeStart>`/
--- `<w:commentRangeEnd>` + `<w:commentReference>` pair, via pandoc's native
--- "comment-start"/"comment-end" class support, plus the corresponding
--- `<w:comment>` entry in word/comments.xml (content-type and relationship
--- registrations are handled by pandoc automatically -- no zip-level
--- post-processing needed).
---
--- For an inline mark (`[>> text]`) with no separate anchor, the mark's own
--- content becomes the comment's message and nothing is left visible in the
--- body -- matching Word's default "comment on the cursor position, no
--- selection" appearance.
---
--- For a block mark (`::: >> ... :::`), the div's own content is both the
--- comment's message *and* stays visible in the body (per
--- document_profile.rs: "there is no separate target content" -- the
--- paragraph is its own anchor), wrapped with the range markers at its
--- first/last paragraph.
---
--- Returns `false` as a second value to stop descent: a comment nested
--- inside another comment must fold into the outer comment's text rather
--- than becoming an independent Word comment (see
--- `profile_extract_block_comment_is_a_leaf`). Reusing the original,
--- not-yet-recursed content as the comment-start Span's message achieves
--- this for free -- any nested quarto-* mark inside is left with its
--- original (writer-unrecognized) class and simply renders as plain text.
local function docx_handle_edit_comment(el)
  local id = next_comment_id(el)
  local attrs = comment_attrs(el, id)

  if el.t == "Span" then
    local start_span = pandoc.Span(el.content, pandoc.Attr("", { "comment-start" }, attrs))
    local end_span = pandoc.Span({}, pandoc.Attr("", { "comment-end" }, { { "id", id } }))
    return pandoc.Inlines({ start_span, end_span }), false
  end

  -- Div: the message is the flattened div content; the body keeps the
  -- original (unwrapped) blocks, with range markers spliced onto the
  -- first/last paragraph.
  local message = pandoc.utils.blocks_to_inlines(el.content)
  local start_span = pandoc.Span(message, pandoc.Attr("", { "comment-start" }, attrs))
  local end_span = pandoc.Span({}, pandoc.Attr("", { "comment-end" }, { { "id", id } }))

  local blocks = {}
  for i, b in ipairs(el.content) do blocks[i] = b end
  if #blocks == 0 then
    return pandoc.Blocks({ pandoc.Para({ start_span, end_span }) }), false
  end

  local first = blocks[1]
  if first.t == "Para" or first.t == "Plain" or first.t == "Header" then
    local new_first = first:clone()
    local content = pandoc.Inlines({ start_span })
    for _, il in ipairs(first.content) do content:insert(il) end
    new_first.content = content
    blocks[1] = new_first
  else
    table.insert(blocks, 1, pandoc.Para({ start_span }))
  end

  local last_idx = #blocks
  local last = blocks[last_idx]
  if last.t == "Para" or last.t == "Plain" or last.t == "Header" then
    local new_last = last:clone()
    local content = pandoc.Inlines({})
    for _, il in ipairs(last.content) do content:insert(il) end
    content:insert(end_span)
    new_last.content = content
    blocks[last_idx] = new_last
  else
    table.insert(blocks, pandoc.Para({ end_span }))
  end

  return pandoc.Blocks(blocks), false
end

--------------------------------------------------------------------------
-- pptx fallback handlers
--------------------------------------------------------------------------

local function xml_escape(s)
  return (s:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"))
end

-- A single flattened raw run: pptx has no per-run home for a marker class
-- alongside pandoc's native Str/Space handling the way docx does, so we
-- hand-build one `<a:r>` from the fully-stringified content. Nested rich
-- formatting inside the marked span/div is lost; this is a documented
-- fallback, not full fidelity.
local function pptx_raw_run(text, rpr_xml)
  local xml = "<a:r><a:rPr" .. rpr_xml .. "/>"
      .. "<a:t xml:space=\"preserve\">" .. xml_escape(text) .. "</a:t></a:r>"
  return pandoc.RawInline("openxml", xml)
end

local function pptx_wrap(el, rpr_xml)
  local text = pandoc.utils.stringify(el)
  local raw = pptx_raw_run(text, rpr_xml)
  if el.t == "Div" then
    return pandoc.Blocks({ pandoc.Para({ raw }) })
  end
  return pandoc.Inlines({ raw })
end

local function pptx_handle_insert(el)
  return pptx_wrap(el, " u=\"sng\"")
end

local function pptx_handle_delete(el)
  return pptx_wrap(el, " strike=\"sngStrike\"")
end

local function pptx_handle_highlight(el)
  local text = pandoc.utils.stringify(el)
  local xml = "<a:r><a:rPr><a:highlight><a:srgbClr val=\"FFFF00\"/></a:highlight></a:rPr>"
      .. "<a:t xml:space=\"preserve\">" .. xml_escape(text) .. "</a:t></a:r>"
  local raw = pandoc.RawInline("openxml", xml)
  if el.t == "Div" then
    return pandoc.Blocks({ pandoc.Para({ raw }) })
  end
  return pandoc.Inlines({ raw })
end

-- No inline-anchored comment concept exists in pptx; render the comment as
-- a bracketed, visually-distinct annotation immediately at the mark's
-- location rather than a real PowerPoint comment.
local function pptx_handle_edit_comment(el)
  local message = pandoc.utils.stringify(el)
  local author = el.attributes["author"]
  local label
  if author then
    label = " [" .. author .. ": " .. message .. "]"
  else
    label = " [comment: " .. message .. "]"
  end
  local xml = "<a:r><a:rPr i=\"1\"><a:solidFill><a:srgbClr val=\"C00000\"/></a:solidFill></a:rPr>"
      .. "<a:t xml:space=\"preserve\">" .. xml_escape(label) .. "</a:t></a:r>"
  local raw = pandoc.RawInline("openxml", xml)
  if el.t == "Div" then
    return pandoc.Blocks({ pandoc.Para({ raw }) }), false
  end
  return pandoc.Inlines({ raw }), false
end

--------------------------------------------------------------------------
-- Dispatch
--------------------------------------------------------------------------

local docx_dispatch = {
  ["quarto-insert"] = docx_handle_insert,
  ["quarto-delete"] = docx_handle_delete,
  ["quarto-highlight"] = docx_handle_highlight,
  ["quarto-edit-comment"] = docx_handle_edit_comment,
}

local pptx_dispatch = {
  ["quarto-insert"] = pptx_handle_insert,
  ["quarto-delete"] = pptx_handle_delete,
  ["quarto-highlight"] = pptx_handle_highlight,
  ["quarto-edit-comment"] = pptx_handle_edit_comment,
}

function dispatch_element(el)
  local dispatch = FORMAT == "docx" and docx_dispatch or pptx_dispatch
  local handler = dispatch[first_class(el)]
  if handler then
    return handler(el)
  end
  return nil
end

return {
  {
    traverse = "topdown",
    Span = dispatch_element,
    Div = dispatch_element,
  },
}
